name: rebuild-website

on:
  push:
    branches:
    - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: install-hugo
      working-directory: /tmp
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
        sudo apt install ./hugo_0.74.3_Linux-64bit.deb
    - uses: actions/checkout@v2
      with:
        ref: test
        submodules: true
    - uses: actions/checkout@v2
      with:
        repository: naotoman/naotoman.github.io
        ref: test
        path: public
    - name: clean-public
      working-directory: ./public
      run: |
        ls -A | grep -v -E '^.git$|^.gitignore$|^CNAME$' | xargs rm -rf
        ls -A
    - name: run-hugo
      run: |
        hugo
    - name: deploy
      working-directory: ./public
      env:
        EMAIL: ${{ secrets.EMAIL }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config user.name "Naoto"
        git config user.email "$EMAIL"
        git add .
        git commit -m "rebuilding site $(date '+%Y/%m/%d %H:%M:%S')"
        echo $ACCESS_TOKEN
        git remote -v
        pwd
        ls
        git push https://naotoman:${ACCESS_TOKEN}@github.com/naotoman/naotoman.github.io.git